
../build/whiskit_gui \
--PRINT 3 \
--CONNECT 1 \
--BLOW 1 \
--DEBUG 0 \
--OBJECT 5 \
--WHISKER_NAMES TEST \
--OBJ_SCALE 1000 \
--file_env "../data/world/whisker_world.obj" \
--ACTIVE 1 \
--SIM_TIME 10000.0 \
--SAVE_VIDEO 0 \
--SAVE 0 \
--ObjX 0 \
--ObjY 0 \
--ObjZ -30 \
--ObjYAW 0 \
--ObjPITCH 0 \
--ObjROLL 0 \
--file_video "../output/ratgame.mp4" \
--dir_out ../output/ratgame