
../build/whiskit_gui \
--PRINT 2 \
--SIM_TIME 0.625 \
--CONNECT 0 \
--CDIST 50 \
--CPITCH -45 \
--CYAW 90 \
--BLOW 1 \
--DEBUG 0 \
--ACTIVE 1 \
--WHISKER_NAMES ALL \
--SAVE_KINEMATICS 0 \
--OBJ_SCALE 100 \
--SAVE_VIDEO 1 \
--SAVE 1 \
--OBJECT 5 \
--file_env "../data/concave/concave40.obj" \
--ObjX 0 \
--ObjY 40 \
--ObjZ -10 \
--ObjYAW 0 \
--ObjPITCH 0 \
--ObjROLL 0.65 \
--file_video "../output/ALL.mp4" \
--dir_out ../output/overtest