
../build/whiskit_gui \
--PRINT 2 \
--SIM_TIME 0.62 \
--CONNECT 0 \
--CDIST 50 \
--CPITCH -0 \
--CYAW 0 \
--BLOW 1 \
--DEBUG 0 \
--ACTIVE 1 \
--WHISKER_NAMES ONE \
--OBJ_SCALE 1000 \
--SAVE_VIDEO 0 \
--SAVE 1 \
--OBJECT 5 \
--file_env "../data/world/whisker_world.obj" \
--ObjX 30 \
--ObjY 30 \
--ObjZ -10 \
--ObjYAW 0 \
--ObjPITCH 0 \
--ObjROLL 0.3 \
--file_video "../output/video_object.mp4" \
--dir_out ../output/time_test