
../build/whiskit_gui \
--PRINT 2 \
--SIM_TIME 0.625 \
--CONNECT 0 \
--CDIST 50 \
--CPITCH -0 \
--CYAW 0 \
--BLOW 1 \
--DEBUG 0 \
--ACTIVE 1 \
--SAVE_KINEMATICS 0 \
--WHISKER_NAMES TEST \
--OBJ_SCALE 100 \
--SAVE_VIDEO 0 \
--SAVE 0 \
--OBJECT 5 \
--file_env "../data/concave/concave40.obj" \
--ObjX 31.5596 \
--ObjY 28.9532 \
--ObjZ -10 \
--ObjYAW 0 \
--ObjPITCH 0 \
--ObjROLL 0.46 \
--file_video "../output/video_object.mp4" \
--dir_out ../output/overtest