
../build/whiskit_gui \
--PRINT 3 \
--BLOW 1 \
--DEBUG 0 \
--OBJECT 5 \
--OBJ_SCALE 200 \
--file_env "../data/natural_objects/scan_06.obj" \
--ACTIVE 1 \
--WHISKER_NAMES RL \
--SIM_TIME 125000.0 \
--POSITION 0 0 0 \
--SAVE_VIDEO 0 \
--SAVE 0 \
--ObjX 0 \
--ObjY 65 \
--ObjZ 0 \
--ObjYAW 0 \
--ObjPITCH 0 \
--ObjROLL 0 \
--file_video "../output/RL.mp4" \
--dir_out ../output/ratgame