
../build/whiskit_gui \
--PRINT 2 \
--CONNECT 1 \
--CDIST 50 \
--CPITCH -0 \
--CYAW 180 \
--BLOW 1 \
--DEBUG 0 \
--OBJECT 5 \
--file_env "../data/environment/scan_95.obj" \
--ACTIVE 1 \
--TIME_STOP 10000.0 \
--SAVE_VIDEO 1 \
--SAVE 1 \
--ObjX 50 \
--ObjY 10 \
--ObjZ 5 \
--ObjYAW 1.57 \
--ObjPITCH -0.7 \
--ObjROLL 0 \
--file_video "../output/ratgame.mp4" \
--dir_out ../output/ratgam