#!/usr/bin/env python3
# import rospy
import subprocess


if __name__ == '__main__':
    # rospy.init_node('run_simulator') 
    cmdstr = "~/Final_Project/ws/src/whiskitphysics/code/scripts/run_user_control.sh"


    subprocess.run([cmdstr])